### ISSUE TITLE
Consider upgrading JsonObject supporting libraries.

### ISSUE THREAD

**Issue by dmeibusch** [CycloneDX/cyclonedx-core-java#163]
In the 1.x stream, there are updated json libraries with new coords since Oracle passed JEE over to Eclipse/Jakarta.

```
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
            <version>1.1.6</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.json</artifactId>
            <version>1.1.6</version>
        </dependency>
```

**Comment by dmeibusch** [comment]
The 2.x stream involves a more complicated package rename, but will give better dependabot (or similar) support going forward:
```
<dependency>
  <groupId>jakarta.json</groupId>
  <artifactId>jakarta.json-api</artifactId>
  <version>2.0.1</version>
</dependency>

<dependency>
  <groupId>org.glassfish</groupId>
  <artifactId>jakarta.json</artifactId>
  <version>2.0.1</version>
</dependency>
```

**Comment by stevespringett** [comment]
Thanks for the info. All these Eclipse package renames are overwhelming, many of which are completely unnecessary IMO.

We're working on the next release of the Core Java library - v6.0 which will support the CycloneDX v1.4 standard. We'll have to see if this is possible in this release, as there may be dependencies that rely on the former coordinates. If not, then this would be an ideal time to make the change.

**Comment by DarthHater** [comment]
@dmeibusch I took a different tact, recently, and swapped these to `JsonNode` from Jackson (since we are using Jackson, we get this for basically free). I found them to be functionally pretty close to the same, but if that causes you grief, please reach out for sure. The org.glassfish and javax libraries we were using had a GPLv2 with classpath exception license, and while it might have been completely fine to use (in my reading as a total not lawyer, it seemed ok), a lot of orgs get really wary when they see the words GPLv2, hence why I removed them.

**Comment by dmeibusch** [comment]
Oh, that's excellent. We obviously have plenty of use of those libraries within Oracle, but it was raising a few red flags for my team.

**Comment by DarthHater** [comment]
I'm going to go ahead and close this issue as you seem to be ok with this direction, feel free to reopen it if you want!
