### ISSUE TITLE
BOM serialisation fails for both JSON and XML

### ISSUE THREAD

**Issue by skhokhlov** [CycloneDX/cyclonedx-core-java#439]
org.cyclonedx:cyclonedx-core-java:9.0.3

For XML:

javax.xml.parsers.ParserConfigurationException: org.cyclonedx.exception.GeneratorException: com.fasterxml.jackson.databind.JsonMappingException: Can not write a field name, expecting a value (through reference chain: org.cyclonedx.model.Bom["component"]->java.util.ArrayList[8]->org.cyclonedx.model.Component["purl"])

<img width="506" alt="Screenshot 2024-06-25 at 12 56 10 PM" src="https://github.com/CycloneDX/cyclonedx-core-java/assets/1503649/8b8574a9-3280-4131-a153-ff471543dab5">

For JSON, output of BomJsonGenerator::toJsonString just empty string.

can be reproduced here: https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/444

**Comment by patveck** [comment]
@skhokhlov I ran into the same issue. Could it be the `LicenseChoice` object you have is empty in the sense that it has neither a non-empty list of licenses nor a license expression? 

While Jackson throws an exception at the `purl` JSON key, the problem actually seems to be the `licenses` key that comes before it. According to [this method](https://github.com/CycloneDX/cyclonedx-core-java/blob/3702283abd718595c069025762979fb9dfcee26b/src/main/java/org/cyclonedx/util/serializer/LicenseChoiceSerializer.java#L148), a `LicenseChoice` that neither a non-empty list of licenses nor a license expression isn't handled correctly: nothing is written, while Jackson has already added `"licenses":` to the JSON output it is generating. 

A possible workaround would be to ensure that in case there's no license information, the `licenses` field of the `Component` object is Java `null` instead of a `LicenseChoice` reference.

**Comment by kennylam91** [comment]
Thanks @patveck , the work-around works for me as well.
