### ISSUE TITLE
Why does Bom.java have schemaVersion?

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-core-java#7]
As a new user, I wonder why `Bom.java` has `schemaVersion` which

1. never seems to be read, and
1. the `schemaVersion` seems to be handled as part of the `BomGenerator` instead.

Moreover, the `schemaVersion` in `Bom.java` is a `String` instead of a `CycloneDxSchema.Version`. Can't `schemaVersion` simply be removed from `Bom.java`?

**Comment by stevespringett** [comment]
schemaVersion is a string so that the model can support milestone releases without having to update all the applications that use this library to parse boms. CycloneDxSchema.Version will eventually be refactored as it assumes XML namespaces, which does not apply to the upcoming JSON schema.

The value of schemaVersion is automatically set, and third party apps do make use of it. Dependency-Track for examples, relies on this value, so it cannot be removed from Bom.java.

**Comment by stevespringett** [comment]
The value of schemaVersion however, is really only applicable when parsing a bom. When generating one, there's no need to populate it.

**Comment by sschuberth** [comment]
Ok, thanks for the clarification.
